"""created hero  powers  table

Revision ID: 8c767f18e001
Revises: e537537b98da
Create Date: 2024-01-28 15:27:43.387916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c767f18e001'
down_revision = 'e537537b98da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_id', sa.Integer(), nullable=True))
        batch_op.drop_column('hero_power_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_power_type', sa.INTEGER(), nullable=True))
        batch_op.drop_column('hero_id')

    # ### end Alembic commands ###
